[platformio]
extra_configs = ../global.ini


[env:esp32dev]
board = esp32dev

; Aquesta línia buida li diu a VS Code: "Ei, aquest projecte fa servir aquest entorn"
; El codi real l'agafarà del global.ini
; Aquesta línia buida li diu a VS Code: "Ei, aquest projecte fa servir aquest entorn"
; El codi real l'agafarà del global.ini